import { Tier } from '../types';
import {
  EXPORT_CANVAS_WIDTH,
  EXPORT_FOOTER_HEIGHT,
  EXPORT_PADDING,
  EXPORT_SCALE,
  EXPORT_TITLE_HEIGHT,
  TIER_CARD_HEIGHT,
  TIER_CARD_TEXT_HEIGHT,
  TIER_CARD_WIDTH,
  TIER_LABEL_HEIGHT,
  TIER_LABEL_WIDTH,
  getExportCanvasHeight,
  getTierCardPosition,
  getTierRowHeight,
} from './exportImageLayout';

type ExportAsImageOptions = {
  tiers: Tier[];
};

type LoadImageResult = {
  image: HTMLImageElement | null;
  ok: boolean;
};

const EXPORT_BACKGROUND = '#1d1d1d';
const TIER_COLORS = ['#ef4444', '#f97316', '#22c55e', '#3b82f6', '#6b7280'];
const TITLE_LOGO_PATH = '/static/logo.png';
const FOOTER_BADGE_PATH = '/static/EXW.png';
const FOOTER_TEXT = 'Generated by https://tier.ygotools.com created by @potato4d';
const IMAGE_LOAD_TIMEOUT_MS = 15000;

const imageCache = new Map<string, Promise<LoadImageResult>>();

const waitForImageLoad = (src: string, timeoutMs: number): Promise<LoadImageResult> => new Promise((resolve) => {
  const image = new Image();
  let settled = false;
  const timeoutId = window.setTimeout(() => {
    finalize({ image: null, ok: false });
  }, timeoutMs);

  function finalize(result: LoadImageResult) {
    if (settled) {
      return;
    }

    settled = true;
    window.clearTimeout(timeoutId);
    resolve(result);
  }

  image.decoding = 'async';
  image.loading = 'eager';
  image.onload = () => finalize({ image, ok: true });
  image.onerror = () => finalize({ image: null, ok: false });
  image.src = src;

  if (image.complete && image.naturalWidth > 0) {
    finalize({ image, ok: true });
  }
});

const loadImage = (src: string, timeoutMs = IMAGE_LOAD_TIMEOUT_MS) => {
  const cached = imageCache.get(src);

  if (cached) {
    return cached;
  }

  const request = waitForImageLoad(src, timeoutMs);
  imageCache.set(src, request);
  return request;
};

const createCanvas = (width: number, height: number) => {
  const canvas = document.createElement('canvas');
  canvas.width = width * EXPORT_SCALE;
  canvas.height = height * EXPORT_SCALE;
  canvas.style.width = `${width}px`;
  canvas.style.height = `${height}px`;
  return canvas;
};

const drawRoundedRect = (
  context: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
) => {
  const r = Math.min(radius, width / 2, height / 2);

  context.beginPath();
  context.moveTo(x + r, y);
  context.arcTo(x + width, y, x + width, y + height, r);
  context.arcTo(x + width, y + height, x, y + height, r);
  context.arcTo(x, y + height, x, y, r);
  context.arcTo(x, y, x + width, y, r);
  context.closePath();
};

const trimText = (
  context: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
) => {
  if (context.measureText(text).width <= maxWidth) {
    return text;
  }

  let trimmed = text;

  while (trimmed.length > 0 && context.measureText(`${trimmed}...`).width > maxWidth) {
    trimmed = trimmed.slice(0, -1);
  }

  return trimmed.length > 0 ? `${trimmed}...` : '...';
};

const drawDeckCard = (
  context: CanvasRenderingContext2D,
  image: HTMLImageElement | null,
  name: string,
  x: number,
  y: number,
) => {
  context.save();
  drawRoundedRect(context, x, y, TIER_CARD_WIDTH, TIER_CARD_HEIGHT, 4);
  context.clip();

  if (image) {
    context.drawImage(image, x, y, TIER_CARD_WIDTH, TIER_CARD_HEIGHT);
  } else {
    context.fillStyle = '#2b2b2b';
    context.fillRect(x, y, TIER_CARD_WIDTH, TIER_CARD_HEIGHT);
    context.strokeStyle = '#4b5563';
    context.strokeRect(x + 0.5, y + 0.5, TIER_CARD_WIDTH - 1, TIER_CARD_HEIGHT - 1);
  }

  context.fillStyle = 'rgba(0, 0, 0, 0.8)';
  context.fillRect(x, y + TIER_CARD_HEIGHT - TIER_CARD_TEXT_HEIGHT, TIER_CARD_WIDTH, TIER_CARD_TEXT_HEIGHT);
  context.restore();

  context.font = 'bold 12px sans-serif';
  context.fillStyle = '#ffffff';
  context.textAlign = 'center';
  context.textBaseline = 'middle';
  context.fillText(
    trimText(context, name, TIER_CARD_WIDTH - 12),
    x + TIER_CARD_WIDTH / 2,
    y + TIER_CARD_HEIGHT - TIER_CARD_TEXT_HEIGHT / 2,
  );
};

const drawTierLabel = (
  context: CanvasRenderingContext2D,
  label: string,
  tierIndex: number,
  y: number,
) => {
  context.fillStyle = TIER_COLORS[tierIndex] ?? TIER_COLORS[TIER_COLORS.length - 1];
  context.fillRect(EXPORT_PADDING, y + EXPORT_PADDING, TIER_LABEL_WIDTH, TIER_LABEL_HEIGHT);

  context.font = 'bold 20px sans-serif';
  context.fillStyle = '#ffffff';
  context.textAlign = 'center';
  context.textBaseline = 'middle';
  context.fillText(label, EXPORT_PADDING + TIER_LABEL_WIDTH / 2, y + EXPORT_PADDING + TIER_LABEL_HEIGHT / 2);
};

const drawTitle = async (context: CanvasRenderingContext2D) => {
  const logo = await loadImage(TITLE_LOGO_PATH);

  if (logo.ok && logo.image) {
    const width = 225;
    const height = 35.5;
    context.drawImage(
      logo.image,
      (EXPORT_CANVAS_WIDTH - width) / 2,
      (EXPORT_TITLE_HEIGHT - height) / 2,
      width,
      height,
    );
    return;
  }

  context.font = 'bold 28px sans-serif';
  context.fillStyle = '#ffffff';
  context.textAlign = 'center';
  context.textBaseline = 'middle';
  context.fillText('Tier Maker', EXPORT_CANVAS_WIDTH / 2, EXPORT_TITLE_HEIGHT / 2);
};

const drawFooter = async (
  context: CanvasRenderingContext2D,
  footerTop: number,
) => {
  const badge = await loadImage(FOOTER_BADGE_PATH);

  context.font = '12px sans-serif';
  context.fillStyle = '#ffffff';
  context.textAlign = 'center';
  context.textBaseline = 'middle';
  context.fillText(FOOTER_TEXT, EXPORT_CANVAS_WIDTH / 2, footerTop + EXPORT_FOOTER_HEIGHT / 2);

  if (badge.ok && badge.image) {
    const badgeWidth = 80;
    const badgeHeight = (badge.image.naturalHeight / badge.image.naturalWidth) * badgeWidth;
    context.drawImage(
      badge.image,
      EXPORT_CANVAS_WIDTH - EXPORT_PADDING - badgeWidth,
      footerTop + (EXPORT_FOOTER_HEIGHT - badgeHeight) / 2,
      badgeWidth,
      badgeHeight,
    );
  }
};

const canvasToBlob = (canvas: HTMLCanvasElement) => new Promise<Blob>((resolve, reject) => {
  canvas.toBlob((blob) => {
    if (blob) {
      resolve(blob);
      return;
    }

    reject(new Error('Failed to render canvas as a PNG blob.'));
  }, 'image/png');
});

const downloadBlob = async (blob: Blob) => {
  const file = new File([blob], 'tier-list.png', { type: 'image/png' });
  const nav = navigator as Navigator & {
    canShare?: (data?: ShareData) => boolean;
    share?: (data?: ShareData) => Promise<void>;
  };

  if (nav.canShare?.({ files: [file] }) && nav.share) {
    await nav.share({
      files: [file],
      title: 'Tier list',
    });
    return;
  }

  const objectUrl = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = file.name;
  document.body.appendChild(link);
  link.click();
  link.remove();

  window.setTimeout(() => {
    window.URL.revokeObjectURL(objectUrl);
  }, 1000);
};

export const exportAsImage = async ({ tiers }: ExportAsImageOptions) => {
  const height = getExportCanvasHeight(tiers);
  const canvas = createCanvas(EXPORT_CANVAS_WIDTH, height);
  const context = canvas.getContext('2d');

  if (!context) {
    throw new Error('Canvas 2D context is not available.');
  }

  context.scale(EXPORT_SCALE, EXPORT_SCALE);
  context.fillStyle = EXPORT_BACKGROUND;
  context.fillRect(0, 0, EXPORT_CANVAS_WIDTH, height);

  await drawTitle(context);

  const allDecks = tiers.flatMap((tier) => tier.decks);
  const imageEntries = await Promise.all(
    allDecks.map(async (deck) => [deck.image, await loadImage(deck.image)] as const),
  );
  const deckImageMap = new Map(imageEntries);

  let cursorY = EXPORT_TITLE_HEIGHT;

  tiers.forEach((tier, tierIndex) => {
    const rowHeight = getTierRowHeight(tier.decks.length);
    drawTierLabel(context, tier.name, tierIndex, cursorY);

    tier.decks.forEach((deck, deckIndex) => {
      const position = getTierCardPosition(deckIndex, cursorY);
      const deckImage = deckImageMap.get(deck.image);
      drawDeckCard(context, deckImage?.image ?? null, deck.name, position.x, position.y);
    });

    cursorY += rowHeight;
  });

  await drawFooter(context, cursorY);

  const blob = await canvasToBlob(canvas);
  await downloadBlob(blob);
};
