import React from 'react';
import TierList from './components/TierList';

const App: React.FC = () => {
  return (
    <div className="container w-full max-w-[880px] mx-auto">
      <h1 className="text-4xl font-bold pt-4 md:pt-8 export-md:pt-8 mb-8 text-center flex items-center justify-center" style={{
        fontFamily: 'Digital Numbers'
      }}><img src="/static/logo.png" alt="Tier Maker" width="225" height="35.5" className='mr-14' /></h1>

      <TierList />

      <details className='text-white mt-4 text-sm ml-4'>
        <summary className='block mb-2'>更新履歴</summary>
          <ul>
          <li>2024/11/05: 【マナドゥム】【キマイラ】【覇王幻奏】【暗黒界】を追加しました。</li>
          <li>2024/10/14: 【霊獣】【ライトロード】を追加しました。</li>
          <li>2024/10/09: 【天盃龍】【インフェルノイド】を追加しました。</li>
          <li>2024/09/16: 【古代の機械】【ヴァリアンツ】を追加しました。</li>
          <li>2024/08/15: 【神碑】を追加しました。</li>
          <li>2024/08/05: 【粛声】を追加しました。</li>
          <li>2024/07/03: センチュリオン/ユベル/エンディミオンを追加しました。</li>
          <li>2024/06/17: v0.1.0 を公開しました。</li>
          </ul>
      </details>

      <a href="https://docs.google.com/forms/d/e/1FAIpQLScn8SCvjob9GXjtwctK6JDdIpdIg2pzX-pMDdNryTBQDsXfhw/viewform?usp=sf_link" target='_blank' className='text-sm underline my-4 inline-block'>テーマ追加希望はこちら</a>

      <div className='flex items-center justify-center'>
        &copy; 2024&nbsp;<a href="https://x.com/potato4d" className='underline'>@potato4d</a>
      </div>

      <footer className='flex px-4 justify-between items-center py-4 opacity-0' style={{
        width: '816px',
        maxWidth: '100%'
      }}>
        <div className='w-20 h-1'></div>
        <div className='text-sm flex-1 text-center'>Generated by <a href="https://tier.ygotools.com" target='_blank' className='underline'>https://tier.ygotools.com</a> created by @potato4d</div>
        <img src="/static/EXW.png" width="80" alt="teamEXTRAWIN" />
      </footer>
    </div>
  );
};

export default App;
