import { Deck, Tier } from './types';

export const SAMPLE_DATA: Tier[] = [
  {
    name: 'Tier1',
    decks: [
      { id: 'killer-tune', name: 'キラーチューン', kana: 'きらーちゅーん', image: '/static/deckimages/killer-tune.png' },
      { id: 'doremi-yummy', name: 'ドレミヤミー', kana: 'どれみやみー', image: '/static/deckimages/doremi-yummy.png' },
    ],
  },
  {
    name: 'Tier2',
    decks: [
      { id: 'vsk9', name: 'VSK9', kana: 'ぶいえすけーないん', image: '/static/deckimages/vsk9.png' },
      { id: 'dracotail', name: 'ドラゴンテイル', kana: 'どらごんている', image: '/static/deckimages/dracotail.png' },
      { id: 'malice', name: 'M∀LICE', kana: 'まりす', image: '/static/deckimages/malice.png' },
      { id: 'gemknight', name: 'ジェムナイト', kana: 'じぇむないと', image: '/static/deckimages/gemknight.png' },
    ],
  },
  {
    name: 'Tier3',
    decks: [
      { id: 'mitsurugi-ryzeal', name: '巳剣ライゼオル', kana: 'みつるぎらいぜおる', image: '/static/deckimages/mitsurugi-ryzeal.png' },
      { id: 'skystriker', name: '閃刀姫', kana: 'せんとうき', image: '/static/deckimages/skystriker.png' },
      { id: 'moonlight', name: '月光', kana: 'むーんらいと', image: '/static/deckimages/moonlight.png' },
    ],
  },
  {
    name: 'Tier4',
    decks: [
      { id: 'tearlaments', name: 'ティアラメンツ', kana: 'てぃあらめんつ', image: '/static/deckimages/tearlaments.png' },
    ],
  },
];

export const INITIAL_AVAILABLE_DECKS: Deck[] = [
  { id: 'onomato-ryzeal', name: 'オノマトライゼオル', kana: 'おのまとらいぜおる', image: '/static/deckimages/onomato-ryzeal.png' },
  { id: 'mitsurugi', name: '巳剣', kana: 'みつるぎ', image: '/static/deckimages/mitsurugi.png' },
  { id: 'yummy', name: 'ヤミー', kana: 'やみー', image: '/static/deckimages/yummy.png' },
  { id: 'orcust', name: 'オルフェゴール', kana: 'おるふぇごーる', image: '/static/deckimages/orcust.png' },
  { id: 'metabeat', name: 'メタビート', kana: 'めたびーと', image: '/static/deckimages/metabeat.png' },
  { id: 'ryzeal', name: 'ライゼオル', kana: 'らいぜおる', image: '/static/deckimages/ryzeal.png' },
  { id: 'tenpai-dragon', name: '天盃龍', kana: 'てんぱいりゅう', image: '/static/deckimages/tenpai-dragon.png' },
  { id: 'voiceless_voice', name: '粛声', kana: 'しゅくせい', image: '/static/deckimages/voiceless_voice.png' },
  { id: 'blue-eyes', name: '青眼', kana: 'ぶるーあいず', image: '/static/deckimages/blue-eyes.png' },
  { id: 'atlantean', name: '海皇', kana: 'かいおう', image: '/static/deckimages/atlantean.png' },
  { id: 'snake-eye', name: 'スネークアイ', kana: 'すねーくあい', image: '/static/deckimages/snake-eye.png' },
  { id: 'mementotlan', name: 'メメント', kana: 'めめんと', image: '/static/deckimages/mementotlan.png' },
  { id: 'white-forest', name: '白き森', kana: 'しろきもり', image: '/static/deckimages/white-forest.png' },
  { id: 'crystron', name: 'クリストロン', kana: 'くりすとろん', image: '/static/deckimages/crystron.png' },
  { id: 'labrynth', name: 'ラビュリンス', kana: 'らびゅりんす', image: '/static/deckimages/labrynth.png' },
  { id: 'punk', name: 'P.U.N.K.', kana: 'ぱんく', image: '/static/deckimages/punk.png' },
  { id: 'centur-ion', name: 'センチュリオン', kana: 'せんちゅりおん', image: '/static/deckimages/centur-ion.png' },
  { id: 'unchained', name: '破械', kana: 'はかい', image: '/static/deckimages/unchained.png' },
  { id: 'ritual-beast', name: '霊獣', kana: 'れいじゅう', image: '/static/deckimages/ritual-beast.png' },
  { id: 'yubel', name: 'ユベル', kana: 'ゆべる', image: '/static/deckimages/yubel.png' },
  { id: 'branded', name: '烙印', kana: 'らくいん', image: '/static/deckimages/branded.png' },
  { id: 'drytron', name: 'ドライトロン', kana: 'どらいとろん', image: '/static/deckimages/drytron.png' },
  { id: 'ice-barrier', name: '氷結界', kana: 'ひょうけっかい', image: '/static/deckimages/ice-barrier.png' },
  { id: 'eldlich', name: 'エルドリッチ', kana: 'えるどりっち', image: '/static/deckimages/eldlich.png' },
  { id: 'dracoslayer', name: '竜剣士', kana: 'りゅうけんし', image: '/static/deckimages/dracoslayer.png' },
  { id: '60gs', name: '60GS', kana: 'ろくじゅうじーえす', image: '/static/deckimages/60gs.png' },
  { id: 'fireking-snake-eye', name: '炎王スネークアイ', kana: 'えんおうすねーくあい', image: '/static/deckimages/fireking-snake-eye.png' },
  { id: 'r-ace', name: 'R-ACE', kana: 'れすきゅーえーす', image: '/static/deckimages/r-ace.png' },
  { id: 'gimmick-puppet', name: 'ギミック・パペット', kana: 'ぎみっくぱぺっと', image: '/static/deckimages/gimmick-puppet.png' },
  { id: 'mannadium', name: 'マナドゥム', kana: 'まなどぅむ', image: '/static/deckimages/mannadium.png' },
  { id: 'chimera', name: 'キマイラ', kana: 'きまいら', image: '/static/deckimages/chimera.png' },
  { id: 'supreme-melodious', name: '覇王幻奏', kana: 'はおうげんそう', image: '/static/deckimages/supreme-melodious.png' },
  { id: 'lightsworn', name: 'ライトロード', kana: 'らいとろーど', image: '/static/deckimages/lightsworn.png' },
  { id: 'spright', name: 'スプライト', kana: 'すぷらいと', image: '/static/deckimages/spright.png' },
  { id: 'runick', name: '神碑', kana: 'るーん', image: '/static/deckimages/runick.png' },
  { id: 'superheavy_samurai', name: '超重武者', kana: 'ちょうじゅうむしゃ', image: '/static/deckimages/superheavy_samurai.png' },
  { id: 'exosister', name: 'エクソシスター', kana: 'えくそしすたー', image: '/static/deckimages/exosister.png' },
  { id: 'ignister', name: '＠イグニスター', kana: 'あっといぐにすたー', image: '/static/deckimages/ignister.png' },
  { id: 'salamangreat', name: '転生炎獣', kana: 'さらまんぐれいと', image: '/static/deckimages/salamangreat.png' },
  { id: 'mathmech', name: '斬機', kana: 'ざんき', image: '/static/deckimages/mathmech.png' },
  { id: 'purrely', name: 'ピュアリィ', kana: 'ぴゅありぃ', image: '/static/deckimages/purrely.png' },
  { id: 'kashtira', name: 'クシャトリラ', kana: 'くしゃとりら', image: '/static/deckimages/kashtira.png' },
  { id: 'others_01', name: 'その他1', kana: 'そのたいち', image: '/static/deckimages/others_01.png' },
  { id: 'others_02', name: 'その他2', kana: 'そのたに', image: '/static/deckimages/others_02.png' },
];
