import { Deck, Tier } from './types';

export const SAMPLE_DATA: Tier[] = [
  {
    name: 'Tier1',
    decks: [
      { id: 'killer-tune', name: 'キラーチューン', image: '/static/deckimages/killer-tune.png' },
      { id: 'doremi-yummy', name: 'ドレミヤミー', image: '/static/deckimages/doremi-yummy.png' },
    ],
  },
  {
    name: 'Tier2',
    decks: [
      { id: 'vsk9', name: 'VSK9', image: '/static/deckimages/vsk9.png' },
      { id: 'dracotail', name: 'ドラゴンテイル', image: '/static/deckimages/dracotail.png' },
      { id: 'malice', name: 'M∀LICE', image: '/static/deckimages/malice.png' },
      { id: 'gemknight', name: 'ジェムナイト', image: '/static/deckimages/gemknight.png' },
    ],
  },
  {
    name: 'Tier3',
    decks: [
      { id: 'mitsurugi-ryzeal', name: '巳剣ライゼオル', image: '/static/deckimages/mitsurugi-ryzeal.png' },
      { id: 'skystriker', name: '閃刀姫', image: '/static/deckimages/skystriker.png' },
      { id: 'moonlight', name: '月光', image: '/static/deckimages/moonlight.png' },
    ],
  },
  {
    name: 'Tier4',
    decks: [
      { id: 'tearlaments', name: 'ティアラメンツ', image: '/static/deckimages/tearlaments.png' },
    ],
  },
];

export const INITIAL_AVAILABLE_DECKS: Deck[] = [
  { id: 'onomato-ryzeal', name: 'オノマトライゼオル', image: '/static/deckimages/onomato-ryzeal.png' },
  { id: 'mitsurugi', name: '巳剣', image: '/static/deckimages/mitsurugi.png' },
  { id: 'yummy', name: 'ヤミー', image: '/static/deckimages/yummy.png' },
  { id: 'orcust', name: 'オルフェゴール', image: '/static/deckimages/orcust.png' },
  { id: 'metabeat', name: 'メタビート', image: '/static/deckimages/metabeat.png' },
  { id: 'ryzeal', name: 'ライゼオル', image: '/static/deckimages/ryzeal.png' },
  { id: 'tenpai-dragon', name: '天盃龍', image: '/static/deckimages/tenpai-dragon.png' },
  { id: 'voiceless_voice', name: '粛声', image: '/static/deckimages/voiceless_voice.png' },
  { id: 'blue-eyes', name: '青眼', image: '/static/deckimages/blue-eyes.png' },
  { id: 'atlantean', name: '海皇', image: '/static/deckimages/atlantean.png' },
  { id: 'snake-eye', name: 'スネークアイ', image: '/static/deckimages/snake-eye.png' },
  { id: 'mementotlan', name: 'メメント', image: '/static/deckimages/mementotlan.png' },
  { id: 'white-forest', name: '白き森', image: '/static/deckimages/white-forest.png' },
  { id: 'crystron', name: 'クリストロン', image: '/static/deckimages/crystron.png' },
  { id: 'labrynth', name: 'ラビュリンス', image: '/static/deckimages/labrynth.png' },
  { id: 'punk', name: 'P.U.N.K.', image: '/static/deckimages/punk.png' },
  { id: 'centur-ion', name: 'センチュリオン', image: '/static/deckimages/centur-ion.png' },
  { id: 'unchained', name: '破械', image: '/static/deckimages/unchained.png' },
  { id: 'ritual-beast', name: '霊獣', image: '/static/deckimages/ritual-beast.png' },
  { id: 'yubel', name: 'ユベル', image: '/static/deckimages/yubel.png' },
  { id: 'branded', name: '烙印', image: '/static/deckimages/branded.png' },
  { id: 'drytron', name: 'ドライトロン', image: '/static/deckimages/drytron.png' },
  { id: 'ice-barrier', name: '氷結界', image: '/static/deckimages/ice-barrier.png' },
  { id: 'eldlich', name: 'エルドリッチ', image: '/static/deckimages/eldlich.png' },
  { id: 'dracoslayer', name: '竜剣士', image: '/static/deckimages/dracoslayer.png' },
  { id: '60gs', name: '60GS', image: '/static/deckimages/60gs.png' },
  { id: 'fireking-snake-eye', name: '炎王スネークアイ', image: '/static/deckimages/fireking-snake-eye.png' },
  { id: 'r-ace', name: 'R-ACE', image: '/static/deckimages/r-ace.png' },
  { id: 'gimmick-puppet', name: 'ギミック・パペット', image: '/static/deckimages/gimmick-puppet.png' },
  { id: 'mannadium', name: 'マナドゥム', image: '/static/deckimages/mannadium.png' },
  { id: 'chimera', name: 'キマイラ', image: '/static/deckimages/chimera.png' },
  { id: 'supreme-melodious', name: '覇王幻奏', image: '/static/deckimages/supreme-melodious.png' },
  { id: 'lightsworn', name: 'ライトロード', image: '/static/deckimages/lightsworn.png' },
  { id: 'spright', name: 'スプライト', image: '/static/deckimages/spright.png' },
  { id: 'runick', name: '神碑', image: '/static/deckimages/runick.png' },
  { id: 'superheavy_samurai', name: '超重武者', image: '/static/deckimages/superheavy_samurai.png' },
  { id: 'exosister', name: 'エクソシスター', image: '/static/deckimages/exosister.png' },
  { id: 'ignister', name: '＠イグニスター', image: '/static/deckimages/ignister.png' },
  { id: 'salamangreat', name: '転生炎獣', image: '/static/deckimages/salamangreat.png' },
  { id: 'mathmech', name: '斬機', image: '/static/deckimages/mathmech.png' },
  { id: 'purrely', name: 'ピュアリィ', image: '/static/deckimages/purrely.png' },
  { id: 'kashtira', name: 'クシャトリラ', image: '/static/deckimages/kashtira.png' },
  { id: 'others_01', name: 'その他1', image: '/static/deckimages/others_01.png' },
  { id: 'others_02', name: 'その他2', image: '/static/deckimages/others_02.png' },
];
